name: Deploy Backend (AWS SAM)

on:
  push:
    branches:
      - main # Uruchamia siÄ™ tylko po wypchniÄ™ciu zmian na gaÅ‚Ä…Åº gÅ‚Ã³wnÄ…

jobs:
  deploy-lambda:
    runs-on: ubuntu-latest

    steps:
      # 1. Pobranie kodu z repozytorium
      - name: ğŸ“¥ Checkout code
        uses: actions/checkout@v4

      # 2. Konfiguracja Å›rodowiska Python (wymagane przez AWS SAM CLI)
      - name: ğŸ Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      # 3. Instalacja narzÄ™dzia AWS SAM
      - name: ğŸ› ï¸ Install AWS SAM CLI
        uses: aws-actions/setup-sam@v2
        with:
          use-installer: true

      # 4. Logowanie do AWS (uÅ¼ywamy kluczy IAM z Secrets)
      - name: ğŸ”‘ Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: eu-west-1 # Upewnij siÄ™, Å¼e to region Twojego SES! MA BYÄ† JAKO GITHUB VARIABLE!!!

      # 5. Budowanie aplikacji (instalacja npm install itp. dzieje siÄ™ tutaj automatycznie)
      - name: ğŸ—ï¸ SAM Build
        run: sam build

      # 6. WdroÅ¼enie na AWS (Injecting Configuration)
      # --resolve-s3: Automatycznie tworzy bucket na kod ÅºrÃ³dÅ‚owy (zipy)
      # --parameter-overrides: Tutaj wstrzykujemy konfiguracjÄ™ z GitHuba do template.yaml
      - name: ğŸš€ SAM Deploy
        run: |
          sam deploy \
            --stack-name contact-form-prod \
            --resolve-s3 \
            --capabilities CAPABILITY_IAM \
            --region eu-west-1 \
            --no-confirm-changeset \
            --no-fail-on-empty-changeset \
            --parameter-overrides \
              EnvType=prod \
              CloudflareKey=${{ secrets.CLOUDFLARE_SECRET_KEY }} \
              SenderEmail="${{ vars.PROD_SENDER_EMAIL }}" \
              RecipientEmail="${{ vars.PROD_RECIPIENT_EMAIL }}" \
